<x-app-layout>
    <x-slot name="title">Create item</x-slot><x-slot name="header">Item studio</x-slot>
    <section class="page-heading"><div><span class="page-kicker">Items / safe creation</span><h1>Create an item from a template.</h1><p>Choose an existing item so CASY can preserve every required linked stat column, then set the new identity.</p></div><div class="heading-actions"><a class="button secondary" href="{{ route('items.index') }}">Back to catalog</a></div></section>
    @if($errors->any())<div class="inline-alert danger"><strong>Item could not be created</strong><span>{{ $errors->first() }}</span></div>@endif
    <div class="editor-grid item-create-grid">
        <section class="panel form-panel"><div class="panel-heading"><div><span class="panel-kicker">Step 1</span><h2>Choose a template</h2></div><span class="status-chip success">Schema aware</span></div><form method="GET" action="{{ route('items.create') }}" class="template-search-form"><label class="field"><span>Search catalog</span><input name="q" value="{{ request('q') }}" placeholder="CodeName or display key"></label><button class="button secondary" type="submit">Find templates</button></form><div class="template-item-list">@forelse($templates as $item)<a class="template-item-row {{ (int)($templateId ?? 0) === (int)$item['ID'] ? 'active' : '' }}" href="{{ route('items.create', ['template' => $item['ID'], 'q' => request('q')]) }}"><span class="template-item-id">{{ $item['ID'] }}</span><span><b>{{ $item['DisplayName'] ?? $item['CodeName128'] }}</b><small>{{ $item['CodeName128'] }}</small></span><span aria-hidden="true">&gt;</span></a>@empty<div class="empty-state"><div class="empty-illustration" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM8 9h8M8 13h5"/></svg></div><h3>No templates found.</h3><p>Try a different search term.</p></div>@endforelse</div></section>
        <aside class="editor-side"><section class="panel clone-panel"><div class="panel-heading"><div><span class="panel-kicker">Step 2</span><h2>New item identity</h2></div><span class="wizard-number">01</span></div>@if($template)<div class="selected-template"><span>Template #{{ $template['row']['ID'] }}</span><strong>{{ $template['row']['NameStrID128'] ?? $template['row']['CodeName128'] }}</strong><code>{{ $template['row']['CodeName128'] }}</code><small>Linked _RefObjItem #{{ $template['row']['Link'] ?? 'none' }}</small></div>@else<div class="inline-alert neutral"><span>Select a template from the list to continue.</span></div>@endif<form method="POST" action="{{ route('items.store') }}" class="clone-form">@csrf<input type="hidden" name="template_id" value="{{ $templateId ?? '' }}"><label class="field"><span>New CodeName128</span><input name="code_name" value="{{ old('code_name', $template ? $template['row']['CodeName128'].'_COPY' : '') }}" maxlength="128" required><small>Must be unique in _RefObjCommon.</small></label><label class="field"><span>Display key</span><input name="name_key" value="{{ old('name_key', $template['row']['NameStrID128'] ?? '') }}" maxlength="128"><small>All other common and linked fields come from the template.</small></label><button class="button primary full" type="submit" @disabled(!$template) onclick="return confirm('Create this item in the live database?')">Create item</button></form></section><section class="panel safety-card"><span class="security-dot"></span><strong>One transaction</strong><p>CASY clones the linked _RefObjItem row first, rewires Common.Link, then inserts the new common row. Failure rolls back both rows.</p></section></aside>
    </div>
</x-app-layout>
