<x-app-layout>
    <x-slot name="title">Edit item</x-slot>
    <x-slot name="header">Item editor</x-slot>
    @if($error)<div class="inline-alert danger"><strong>Item editor unavailable</strong><span>{{ $error }}</span></div>@endif
    @if($record)
        @php($row = $record['row']) @php($columns = $record['columns']) @php($linked = $record['linked'] ?? null)
        <section class="page-heading"><div class="item-edit-heading"><div class="item-edit-icon">@if($icon)<img src="{{ route('icons.thumbnail', $icon) }}" alt="">@else<span aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/></svg></span>@endif</div><div><span class="page-kicker">Items / live record</span><h1>{{ $row['NameStrID128'] ?? $row['CodeName128'] ?? 'Item '.$row['ID'] }}</h1><p>Record <code>#{{ $row['ID'] }}</code> from <code>{{ $record['database'] }}</code>. Fields are loaded from your actual table metadata.</p></div></div><div class="heading-actions">@if($returnTo)<a class="button secondary" href="{{ $returnTo }}">Back to NPC shop</a>@else<a class="button secondary" href="{{ route('items.index') }}">Back to catalog</a>@endif<button class="button primary" type="submit" form="item-edit-form">Save changes</button></div></section>
        <div class="editor-grid"><section class="panel form-panel"><div class="panel-heading"><div><span class="panel-kicker">Mapped columns</span><h2>Edit item fields</h2></div><span class="status-chip success">Schema aware</span></div><form id="item-edit-form" method="POST" action="{{ route('items.update', $row['ID']) }}" class="editor-fields">@csrf @method('PUT')@if($returnTo)<input type="hidden" name="from" value="npc-shops"><input type="hidden" name="npc" value="{{ request('npc') }}"><input type="hidden" name="tab" value="{{ request('tab') }}">@endif
                @foreach($columns as $column => $meta) @php($type = strtolower((string)($meta['type_name'] ?? ''))) @php($blocked = in_array($type, ['timestamp','rowversion','image','text','ntext','xml','geography','geometry','hierarchyid'], true) || $column === 'ID' || !empty($meta['is_identity']) || !empty($meta['is_computed'])) @if(!$blocked && array_key_exists($column, $row))<label class="field"><span>{{ $column }} @if(!$meta['is_nullable'])<b class="required-mark">*</b>@endif</span>@if($type === 'bit')<select name="fields[{{ $column }}]"><option value="1" @selected((string)$row[$column] === '1')>True</option><option value="0" @selected((string)$row[$column] === '0')>False</option></select>@elseif(in_array($type, ['tinyint','smallint','int','bigint','decimal','numeric','money','smallmoney','float','real'], true))<input type="number" name="fields[{{ $column }}]" value="{{ old('fields.'.$column, is_scalar($row[$column]) ? $row[$column] : '') }}" step="{{ in_array($type, ['decimal','numeric','money','smallmoney','float','real']) ? 'any' : '1' }}" @if(!$meta['is_nullable']) required @endif>@else<input name="fields[{{ $column }}]" value="{{ old('fields.'.$column, is_scalar($row[$column]) ? $row[$column] : '') }}" @if(!$meta['is_nullable']) required @endif>@endif<small>{{ $meta['type_name'] }} - {{ $meta['is_nullable'] ? 'nullable' : 'required' }}</small></label>@endif @endforeach
                @if($linked)<div class="editor-section-title"><span class="panel-kicker">Linked item details</span><h3>_RefObjItem #{{ $linked['row']['ID'] }}</h3><p>Combat, requirements, durability, stacking and item-class values linked through Common.Link.</p></div>@foreach($linked['columns'] as $column => $meta) @php($type = strtolower((string)($meta['type_name'] ?? ''))) @php($blocked = in_array($type, ['timestamp','rowversion','image','text','ntext','xml','geography','geometry','hierarchyid'], true) || $column === 'ID' || !empty($meta['is_identity']) || !empty($meta['is_computed'])) @if(!$blocked && array_key_exists($column, $linked['row']))<label class="field"><span>{{ $column }} @if(!$meta['is_nullable'])<b class="required-mark">*</b>@endif</span>@if($type === 'bit')<select name="details[{{ $column }}]"><option value="1" @selected((string)$linked['row'][$column] === '1')>True</option><option value="0" @selected((string)$linked['row'][$column] === '0')>False</option></select>@elseif(in_array($type, ['tinyint','smallint','int','bigint','decimal','numeric','money','smallmoney','float','real'], true))<input type="number" name="details[{{ $column }}]" value="{{ old('details.'.$column, is_scalar($linked['row'][$column]) ? trim((string)$linked['row'][$column]) : '') }}" step="{{ in_array($type, ['decimal','numeric','money','smallmoney','float','real']) ? 'any' : '1' }}" @if(!$meta['is_nullable']) required @endif>@else<input name="details[{{ $column }}]" value="{{ old('details.'.$column, is_scalar($linked['row'][$column]) ? trim((string)$linked['row'][$column]) : '') }}" @if(!$meta['is_nullable']) required @endif>@endif<small>{{ $meta['type_name'] }} - {{ $meta['is_nullable'] ? 'nullable' : 'required' }}</small></label>@endif @endforeach @endif
            </form></section><aside class="editor-side"><section class="panel clone-panel"><div class="panel-heading"><div><span class="panel-kicker">Fast creation</span><h2>Clone this item</h2></div><span class="wizard-number">02</span></div><p>CASY copies the complete compatible row, keeps identity and foreign-key rules intact, and lets you change only the fields you choose.</p><form method="POST" action="{{ route('items.clone', $row['ID']) }}" class="clone-form">@csrf@if($returnTo)<input type="hidden" name="from" value="npc-shops"><input type="hidden" name="npc" value="{{ request('npc') }}"><input type="hidden" name="tab" value="{{ request('tab') }}">@endif<label class="field"><span>New code name</span><input name="fields[CodeName128]" value="{{ old('fields.CodeName128', ($row['CodeName128'] ?? '').'_COPY') }}" required><small>Use a unique code in your catalog.</small></label><label class="field"><span>Display key (optional)</span><input name="fields[NameStrID128]" value="{{ old('fields.NameStrID128', $row['NameStrID128'] ?? '') }}"><small>Other values are copied from the source item.</small></label><button class="button dark full" type="submit" onclick="return confirm('Clone this item into the live database?')">Clone into catalog</button></form></section><section class="panel safety-card"><span class="security-dot"></span><strong>Writes are audited</strong><p>Every update and clone stores the operation, entity, generated SQL template and result in CASY Logs.</p><a href="{{ route('logs.index') }}">View audit trail <span aria-hidden="true">&rarr;</span></a></section></aside></div>
    @endif
</x-app-layout>
