<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KMTGuard.LicenseAdmin\KMTGuard.LicenseAdmin.csproj" />
    <ProjectReference Include="..\KMTGuard.Licensing\KMTGuard.Licensing.csproj" />
    <ProjectReference Include="..\KMTGuard.Updater\KMTGuard.Updater.csproj" />
  </ItemGroup>
</Project>
