using System.Diagnostics;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text;

var repoRoot = args.Length > 0
    ? Path.GetFullPath(args[0])
    : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", ".."));
var secretsRoot = Path.Combine(
    Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),
    "KMTGuardLicensing",
    "Secrets");
Directory.CreateDirectory(secretsRoot);

var privateKeyPath = Path.Combine(secretsRoot, "license-signing-key.pk8");
var adminTokenPath = Path.Combine(secretsRoot, "admin-api-token.txt");
using var rsa = RSA.Create(3072);
if (File.Exists(privateKeyPath))
{
    rsa.ImportPkcs8PrivateKey(File.ReadAllBytes(privateKeyPath), out _);
}
else
{
    File.WriteAllBytes(privateKeyPath, rsa.ExportPkcs8PrivateKey());
}

if (!File.Exists(adminTokenPath))
    File.WriteAllText(adminTokenPath, Convert.ToHexString(RandomNumberGenerator.GetBytes(32)));

TryRestrictAcl(secretsRoot);
TryRestrictAcl(privateKeyPath);
TryRestrictAcl(adminTokenPath);

var parameters = rsa.ExportParameters(false);
var modulus = parameters.Modulus ?? throw new InvalidOperationException("RSA modulus was not generated.");
var exponent = parameters.Exponent ?? throw new InvalidOperationException("RSA exponent was not generated.");
var keyId = Convert.ToHexString(SHA256.HashData(modulus.Concat(exponent).ToArray()))[..16];

var managedPath = Path.Combine(repoRoot, "KMTGuard.Licensing", "Generated", "TrustedLicenseKey.g.cs");
Directory.CreateDirectory(Path.GetDirectoryName(managedPath)!);
File.WriteAllText(managedPath, $$"""
// Generated by KMTGuard.LicenseKeyTool. Do not place the private key in source control.
namespace KMTGuard.Licensing;

internal static class TrustedLicenseKey
{
    public const string KeyId = "{{keyId}}";
    public const string ModulusBase64 = "{{Convert.ToBase64String(modulus)}}";
    public const string ExponentBase64 = "{{Convert.ToBase64String(exponent)}}";
}
""");

var nativePath = Path.Combine(repoRoot, "native", "KMTGuard.Licensing.Native", "TrustedLicenseKey.generated.h");
Directory.CreateDirectory(Path.GetDirectoryName(nativePath)!);
File.WriteAllText(nativePath, $$"""
#pragma once

// Generated by KMTGuard.LicenseKeyTool. The private key exists only on the owner VPS.
static const char KMT_LICENSE_KEY_ID[] = "{{keyId}}";
static const unsigned char KMT_LICENSE_RSA_MODULUS[] = {
{{FormatBytes(modulus)}}
};
static const unsigned long KMT_LICENSE_RSA_MODULUS_SIZE = sizeof(KMT_LICENSE_RSA_MODULUS);
static const unsigned long KMT_LICENSE_RSA_EXPONENT = {{ReadExponent(exponent)}}UL;
""");

Console.WriteLine($"KMTGuard licensing key is ready. Key ID: {keyId}");
Console.WriteLine($"Private key location: {privateKeyPath}");
Console.WriteLine("Only the public verification key was written into the source tree.");

static string FormatBytes(byte[] bytes)
{
    var lines = bytes.Chunk(16)
        .Select(chunk => "    " + string.Join(", ", chunk.Select(value => $"0x{value:X2}")));
    return string.Join("," + Environment.NewLine, lines);
}

static uint ReadExponent(byte[] exponent)
{
    uint value = 0;
    foreach (var item in exponent)
        value = (value << 8) | item;
    return value;
}

static void TryRestrictAcl(string path)
{
    if (!OperatingSystem.IsWindows())
        return;

    try
    {
        var currentUser = WindowsIdentity.GetCurrent().Name;
        var directoryRights = Directory.Exists(path) ? "(OI)(CI)F" : "F";
        using var process = Process.Start(new ProcessStartInfo
        {
            FileName = "icacls.exe",
            Arguments = $"\"{path}\" /inheritance:r /grant:r \"SYSTEM:{directoryRights}\" \"Administrators:{directoryRights}\" \"{currentUser}:{directoryRights}\"",
            UseShellExecute = false,
            CreateNoWindow = true
        });
        process?.WaitForExit(10_000);
    }
    catch
    {
    }
}
