<x-app-layout>
    <x-slot name="title">Dashboard</x-slot>
    <x-slot name="header">Server overview</x-slot>
    <section class="page-heading"><div><span class="page-kicker">Owner workspace</span><h1>Your server, clearly in view.</h1><p>CASY gives you a visual, audited workspace for the content and players that power your Silkroad server.</p></div><div class="heading-actions"><a href="{{ route('live.index') }}" class="button secondary">Live control</a><a href="{{ route('items.index') }}" class="button primary">Open item studio</a></div></section>
    @if(!$profile)<section class="setup-banner"><div class="setup-icon">01</div><div><span>First step</span><h2>Connect your SQL Server to unlock every studio.</h2><p>Credentials are encrypted in CASY and the first pass only inspects the schema.</p></div><a class="button white" href="{{ route('server-profile.index') }}">Connect server</a></section>@endif
    <section class="metric-grid">@foreach ([['Items', $metrics['items'], 'orange', 'Reference objects ready to edit'], ['Characters', $metrics['characters'], 'green', 'Player records detected'], ['NPC objects', $metrics['npcs'], 'cyan', 'Interactive world objects'], ['Worlds', $metrics['worlds'], 'blue', 'Instance worlds mapped'], ['Guilds', $metrics['guilds'], 'violet', 'Guild records available'], ['DDJ icons', $metrics['icons'], 'blue', 'Indexed visual assets']] as [$label,$value,$tone,$hint])<article class="metric-card"><span class="metric-mark {{ $tone }}"></span><div class="metric-label">{{ $label }}</div><div class="metric-value">{{ $value === null ? '-' : number_format($value) }}</div><div class="metric-hint">{{ $hint }}</div></article>@endforeach</section>
    <section class="dashboard-columns"><div class="panel"><div class="panel-heading"><div><span class="panel-kicker">Workspaces</span><h2>Continue working</h2></div><span class="muted-label">Specialized tools</span></div><div class="module-list">
        <a href="{{ route('items.index') }}" class="module-row"><span class="module-icon"><svg viewBox="0 0 24 24"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4.5 7.5 7.5 4 7.5-4"/></svg></span><span><strong>Item Studio</strong><small>Search, compare, edit and clone game items with their visual assets.</small></span><span class="module-state ready">Ready</span><span class="row-arrow" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></span></a>
        <a href="{{ route('npc-shops.index') }}" class="module-row"><span class="module-icon"><svg viewBox="0 0 24 24"><path d="M4 10h16l-1 10H5L4 10Z"/><path d="M6 10 7 4h10l1 6"/></svg></span><span><strong>NPC Shop Studio</strong><small>Open the NPC hierarchy, tabs and item slots in one workspace.</small></span><span class="module-state ready">Ready</span><span class="row-arrow" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></span></a>
        <a href="{{ route('icons.index') }}" class="module-row"><span class="module-icon"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m4 17 5-5 3 3 2-2 6 6"/></svg></span><span><strong>DDJ Icon Library</strong><small>Scan, filter and preview every extracted item icon.</small></span><span class="module-state ready">Ready</span><span class="row-arrow" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></span></a>
        <a href="{{ route('regions.index') }}" class="module-row"><span class="module-icon"><svg viewBox="0 0 24 24"><path d="M3 6.5 9 4l6 2.5L21 4v13.5L15 20l-6-2.5L3 20V6.5Z"/><path d="M9 4v13.5M15 6.5V20"/></svg></span><span><strong>Areas &amp; Region Studio</strong><small>Preview and clone worlds, mappings and starts safely.</small></span><span class="module-state ready">Ready</span><span class="row-arrow" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></span></a>
    </div></div><div class="panel"><div class="panel-heading"><div><span class="panel-kicker">Audit trail</span><h2>Recent activity</h2></div><a class="muted-label" href="{{ route('logs.index') }}">View all</a></div><div class="activity-list">@forelse($recentActions as $action)<div class="activity-row"><span class="activity-dot"></span><span><strong>{{ str_replace('.', ' / ', $action->action) }}</strong><small>{{ $action->created_at->diffForHumans() }}</small></span><span class="activity-status">{{ ucfirst($action->status) }}</span></div>@empty<div class="empty-compact"><p>No changes yet.<br>Your audited actions will appear here.</p></div>@endforelse</div></div></section>
</x-app-layout>
