#pragma once

#define KMTGUARD_VERSION_MAJOR 6
#define KMTGUARD_VERSION_MINOR 3
#define KMTGUARD_VERSION_PATCH 9
#define KMTGUARD_VERSION_REVISION 0

#define KMTGUARD_VERSION_RESOURCE 6,3,9,0
#define KMTGUARD_VERSION_STRING "6.3.9"
#define KMTGUARD_FILE_VERSION_STRING "6.3.9.0"
#define KMTGUARD_VERSION_WSTRING L"6.3.9"
