#pragma once

#define KMTGUARD_VERSION_MAJOR 6
#define KMTGUARD_VERSION_MINOR 0
#define KMTGUARD_VERSION_PATCH 0
#define KMTGUARD_VERSION_REVISION 0

#define KMTGUARD_VERSION_RESOURCE 6,0,0,0
#define KMTGUARD_VERSION_STRING "6.0.0"
#define KMTGUARD_FILE_VERSION_STRING "6.0.0.0"
#define KMTGUARD_VERSION_WSTRING L"6.0.0"
