<x-app-layout>
    <x-slot name="title">Server settings</x-slot>
    <x-slot name="header">Connection &amp; schema</x-slot>

    <section class="page-heading"><div><span class="page-kicker">Foundation</span><h1>Connect your game database.</h1><p>CASY reads your SQL Server structure and adapts the studio to the tables you already use.</p></div><div class="heading-actions"><span class="security-note"><span class="security-dot"></span>Credentials encrypted</span></div></section>

    <div class="settings-grid">
        <section class="panel form-panel"><div class="panel-heading"><div><span class="panel-kicker">SQL Server</span><h2>Server profile</h2></div><span class="status-chip {{ $profile?->connection_status === 'connected' ? 'success' : 'neutral' }}">{{ $profile?->connection_status === 'connected' ? 'Connected' : ($profile?->connection_status === 'failed' ? 'Needs attention' : 'Not tested') }}</span></div>
            @if($profile?->connection_error)<div class="inline-alert danger"><strong>Last test failed</strong><span>{{ $profile->connection_error }}</span></div>@endif
            @if($profile?->username === 'sa' || (!$profile && ($defaults['username'] ?? '') === 'sa'))<div class="inline-alert warning"><strong>Daily login uses the SQL administrator.</strong><span>Create a dedicated least-privilege login for CASY before production use. Emergency credentials should never be stored here.</span></div>@endif
            <form method="POST" action="{{ route('server-profile.store') }}" class="form-stack">@csrf
                <div class="field-grid two"><label class="field"><span>Profile name</span><input name="name" value="{{ old('name', $profile?->name ?? ($defaults['name'] ?? 'My SRO server')) }}" required placeholder="Production server"><small>A friendly name shown in the sidebar.</small></label><label class="field"><span>Host / IP</span><input name="host" value="{{ old('host', $profile?->host ?? ($defaults['host'] ?? '127.0.0.1')) }}" required placeholder="127.0.0.1 or SQL host"><small>Use the SQL Server host visible to Laragon.</small></label></div>
                <div class="field-grid three"><label class="field"><span>Port</span><input name="port" type="number" min="1" max="65535" value="{{ old('port', $profile?->port ?? ($defaults['port'] ?? 1433)) }}" required></label><label class="field"><span>Username</span><input name="username" value="{{ old('username', $profile?->username ?? ($defaults['username'] ?? '')) }}" required autocomplete="username"><small>Use a dedicated least-privilege SQL login for daily operations.</small></label><label class="field"><span>Password</span><input name="password" type="password" placeholder="{{ $profile ? 'Leave blank to keep current' : 'Use the configured SQL password' }}" autocomplete="new-password"><small>Stored encrypted; never shown back to the browser.</small></label></div>
                <div class="form-divider"><span>Database mapping</span><small>Leave blank and CASY will suggest names after the first test.</small></div>
                <div class="field-grid four"><label class="field"><span>Account DB</span><input name="account_database" value="{{ old('account_database', $profile?->account_database ?? ($defaults['account_database'] ?? 'SRO_VT_ACCOUNT')) }}" placeholder="SRO_VT_ACCOUNT"></label><label class="field"><span>Shard DB</span><input name="shard_database" value="{{ old('shard_database', $profile?->shard_database ?? ($defaults['shard_database'] ?? 'SRO_VT_SHARD')) }}" placeholder="SRO_VT_SHARD"></label><label class="field"><span>Log DB</span><input name="log_database" value="{{ old('log_database', $profile?->log_database ?? ($defaults['log_database'] ?? 'SRO_VT_SHARDLOG')) }}" placeholder="SRO_VT_SHARDLOG"></label><label class="field"><span>Proxy / custom DB</span><input name="proxy_database" value="{{ old('proxy_database', $profile?->proxy_database ?? ($defaults['proxy_database'] ?? 'KMTGUARD')) }}" placeholder="KMTGUARD"></label></div>
                <div class="field-grid two"><label class="field"><span>DDJ icon root</span><input name="icon_root" value="{{ old('icon_root', $profile?->icon_root ?? ($defaults['icon_root'] ?? '')) }}" placeholder="C:\\SRO\\Media\\icon"><small>CASY recursively scans .ddj files from this folder.</small></label><div class="toggle-stack"><label class="toggle"><input type="checkbox" name="encrypt_connection" value="1" @checked(old('encrypt_connection', $profile?->encrypt_connection ?? true))><span></span><b>Encrypt connection</b><small>Recommended for remote SQL Server.</small></label><label class="toggle"><input type="checkbox" name="trust_server_certificate" value="1" @checked(old('trust_server_certificate', $profile?->trust_server_certificate ?? false))><span></span><b>Trust server certificate</b><small>Keep off when the SQL certificate is trusted.</small></label></div></div>
                <div class="form-actions"><span class="muted-label">Saving does not modify game data.</span><button class="button primary" type="submit">Save profile</button></div>
            </form>
        </section>

        <aside class="settings-side"><section class="panel discovery-panel"><div class="panel-heading"><div><span class="panel-kicker">Connection wizard</span><h2>Discover safely</h2></div><span class="wizard-number">01</span></div><p>First CASY connects to <code>master</code>, lists online databases, then counts the tables it recognises. It never writes to your game database during discovery.</p><form method="POST" action="{{ route('server-profile.test') }}">@csrf<button class="button dark full" type="submit" @disabled(!$profile)>Test &amp; discover schema</button></form>@if(!$profile)<small class="side-hint">Save the profile first to enable discovery.</small>@endif</section>
            @if($profile?->schema_stats)<section class="panel schema-panel"><div class="panel-heading"><div><span class="panel-kicker">Last inspection</span><h2>What CASY found</h2></div><span class="status-chip success">{{ $profile->last_tested_at?->diffForHumans() }}</span></div><div class="schema-summary"><div><strong>{{ number_format($profile->schema_stats['table_count'] ?? 0) }}</strong><span>tables</span></div><div><strong>{{ number_format($profile->schema_stats['column_count'] ?? 0) }}</strong><span>columns</span></div><div><strong>{{ number_format($profile->schema_stats['foreign_key_count'] ?? 0) }}</strong><span>relations</span></div></div><div class="capability-list">@foreach(($profile->schema_stats['capabilities'] ?? []) as $capability => $state) @php($ready = is_array($state) ? ($state['ready'] ?? false) : (bool) $state)<div><span>{{ str($capability)->replace('_', ' ')->title() }}</span><b class="capability {{ $ready ? 'on' : 'off' }}">{{ $ready ? 'Detected' : 'Not found' }}</b></div>@endforeach</div>@if(!empty($profile->schema_stats['relations']))<div class="relation-preview"><span class="panel-kicker">Sample foreign keys</span>@foreach(array_slice($profile->schema_stats['relations'], 0, 4) as $relation)<div><code>{{ $relation['table_name'] }}.{{ $relation['column_name'] }}</code><span>-> {{ $relation['referenced_table'] }}.{{ $relation['referenced_column'] }}</span></div>@endforeach</div>@endif</section>@endif
        </aside>
    </div>
</x-app-layout>
